resolver: lts-9.0
flags:
  xmonad-contrib:
    testing: false
    use_xft: true
  xmonad:
    testing: false
  xmobar:
    with_dbus: true
    with_threaded: true
    with_utf8: true
    with_xft: true
    with_mpd: true
    with_mpris: true
    with_inotify: true
    with_alsa: true
    with_xpm: true
    with_weather: true
    with_conduit: true

packages:
  - xmonad
  - xmonad-contrib
  - xmobar
